### ISSUE TITLE
License key issue

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/WPPR-easy-preloader#7]
@selul We have an issue with the key activation. You can not activate your license for this add-on plugin. I have tried many times and doesn't work. I think the problem is from the update system, can you please check this? 

Let me know when you'll find the issue.

**Comment by selul** [comment]
@mileamadalin it should work now, please try to activate now.

**Comment by selul** [comment]
@mileamadalin dont forget to close the ticket when is done
